#!/usr/bin/env python3
"""
B站Cookie获取辅助工具 v1.0
用法：
  1. 在Windows/Mac电脑上登录B站
  2. 用Chrome浏览器的Cookie-Editor扩展导出Netscape格式
  3. 把cookie文件上传到服务器
  4. 运行: python3 get_cookies.py --import cookie.txt --export cookies.json
  5. config.json 中的 cookie_file 指向 cookies.json

或者直接使用（会启动浏览器引导登录并保存cookie）：
  python3 get_cookies.py --auto
"""

import json
import argparse
import re
import sys
from pathlib import Path
from datetime import datetime, timezone, timedelta


def netscape_to_json(netscape_file: str) -> list:
    """将Netscape格式的cookie转换为JSON"""
    cookies = []
    with open(netscape_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) >= 7:
                try:
                    # Netscape格式: domain flag path secure expiry name value
                    expiry = int(parts[4]) if parts[4].isdigit() else 0
                    cookie = {
                        "domain": parts[0],
                        "name": parts[5],
                        "value": parts[6],
                        "path": parts[2],
                        "secure": parts[3].lower() == "true",
                        "httpOnly": False,
                        "sameSite": "Lax",
                        "expirationDate": expiry
                    }
                    cookies.append(cookie)
                except (IndexError, ValueError):
                    continue
    return cookies


def json_to_netscape(cookies: list, output_file: str):
    """将JSON格式的cookie转换为Netscape格式"""
    lines = ["# Netscape HTTP Cookie File", "# Generated by BiliLottery Cookie Tool"]
    for c in cookies:
        domain = c.get("domain", ".bilibili.com")
        if not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = int(c.get("expirationDate", 0)) or int(
            (datetime.now(timezone.utc) + timedelta(days=30)).timestamp())
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
    print(f"已导出Netscape格式: {output_file} ({len(cookies)} 条cookie)")


def auto_login():
    """自动启动浏览器引导登录并保存cookie"""
    import undetected_chromedriver as uc
    import time

    cookie_path = input("请输入cookie保存路径 [默认: ./cookies.json]: ").strip() or "./cookies.json"
    print("启动浏览器...")

    options = uc.ChromeOptions()
    options.add_argument("--window-size=1280,800")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])

    driver = uc.Chrome(options=options, version_main=None)
    try:
        print("请手动登录B站（扫码或密码）...")
        driver.get("https://passport.bilibili.com/login")
        input("登录完成后按回车继续...")

        # 访问B站首页确认登录成功
        driver.get("https://www.bilibili.com")
        time.sleep(2)
        if "login" in driver.current_url:
            print("登录似乎未成功，请重试")
            return

        cookies = driver.get_cookies()
        with open(cookie_path, 'w', encoding='utf-8') as f:
            json.dump(cookies, f, ensure_ascii=False, indent=2)
        print(f"Cookie已保存到: {cookie_path} ({len(cookies)} 条)")

    finally:
        driver.quit()


def main():
    parser = argparse.ArgumentParser(description="B站Cookie转换工具")
    parser.add_argument("--import", dest="import_file", help="导入Netscape格式的cookie文件")
    parser.add_argument("--export", dest="export_file", default="cookies.json", help="导出JSON格式的cookie文件")
    parser.add_argument("--auto", action="store_true", help="自动启动浏览器引导登录")
    parser.add_argument("--to-netscape", help="将JSON cookie转换为Netscape格式")
    args = parser.parse_args()

    if args.auto:
        auto_login()
        return

    if args.import_file:
        cookies = netscape_to_json(args.import_file)
        with open(args.export_file, 'w', encoding='utf-8') as f:
            json.dump(cookies, f, ensure_ascii=False, indent=2)
        print(f"转换完成: {args.import_file} -> {args.export_file} ({len(cookies)} 条cookie)")
        print("请在config.json中设置: \"cookie_file\": \"", args.export_file, "\"")
        return

    if args.to_netscape:
        with open(args.to_netscape, 'r', encoding='utf-8') as f:
            cookies = json.load(f)
        output = args.to_netscape.replace('.json', '.txt')
        json_to_netscape(cookies, output)
        return

    parser.print_help()


if __name__ == "__main__":
    main()
